"""
Structured Schemas for Agentic AI Orchestration Layer.

Defines strict typed data containers for observations (FACTS), hypotheses (SPECULATION),
actions, investigation plans, candidate model proposals, and investigation reports.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass(slots=True)
class AgentObservation:
    """
    Empirical fact observed by formal analysis or controlled tools.
    """
    fact_id: str
    source_tool: str
    description: str
    details: dict[str, Any] = field(default_factory=dict)
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass(slots=True)
class AgentHypothesis:
    """
    AI-generated speculation or hypothesis. Explicitly separated from observed facts.
    """
    hypothesis_id: str
    statement: str
    confidence: float
    supporting_fact_ids: list[str] = field(default_factory=list)
    reasoning: list[str] = field(default_factory=list)


@dataclass(slots=True)
class AgentAction:
    """
    Structured tool call request emitted by an agent.
    """
    action_type: str
    tool_name: str
    parameters: dict[str, Any] = field(default_factory=dict)


@dataclass(slots=True)
class InvestigationPlan:
    """
    Bounded step-by-step investigation plan generated by InvestigationPlanner.
    """
    investigation_id: str
    target_event: str
    steps: list[str] = field(default_factory=list)
    max_steps: int = 10


@dataclass(slots=True)
class CandidateModelProposal:
    """
    Structured proposal for protocol model graph changes generated by ModelProposalAgent.

    NOTE: This object represents an UNVALIDATED proposal and CANNOT mutate the live model directly.
    """
    proposal_id: str
    parent_model_version: str
    proposed_transitions: list[dict[str, Any]] = field(default_factory=list)
    evidence_ids: list[str] = field(default_factory=list)
    reason: str = ""
    confidence: float = 0.0
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


@dataclass(slots=True)
class InvestigationResult:
    """
    Final structured investigation output produced by an agent workflow.
    """
    investigation_id: str
    event_type: str
    classification: str
    observed_facts: list[AgentObservation] = field(default_factory=list)
    ai_hypotheses: list[AgentHypothesis] = field(default_factory=list)
    severity_recommendation: str = "BENIGN"
    action_recommendation: str = "NO_ACTION"
    proposal: CandidateModelProposal | None = None
    explanation: str = ""
    steps_executed: int = 0
    tools_used: list[str] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
